### ISSUE TITLE
Script not working after Slack update

### ISSUE THREAD

**Issue by monsieurTut** [fsavje/math-with-slack#13]
Hello!
I use your script for my Slack app on Ubuntu 16. It worked fine until I updated my packages. I guess the Slack package must have been updated and it stopped rendering math. I rerun your script as mentioned in the doc and restarted slack, but then the slack window was completely blank.
I uninstalled and reinstalled the Slack app, which displayed correctly again. Then I ran your script again and started Slack, but still got a blank window.
I have this version of Slack: 2.6.0 64-bit Beta Channel

**Comment by fsavje** [comment]
Thank you @monsieurTut for the bug report, and sorry for being slow to get to this. With the help of @gauss256, this problem is solved now. See #12
