### ISSUE TITLE
Wrong Windows directory picked for installation

### ISSUE THREAD

**Issue by gauss256** [fsavje/math-with-slack#17]
The installer sorts the candidate installation directories by name, but due to the way Slack updates itself, this can lead to the wrong directory being chosen.

For example, on my system I have

    2017-06-07  09:31 PM    <DIR>          app-2.6.3
    2017-06-02  07:19 PM    <DIR>          app-2.6.3-beta2622578f

The installer picks `app-2.6.3-beta2622578f` for SLACK_DIR but it should use `app-2.6.3` because it is more recent.

You can workaround this by specifying the Slack directory on the command line. I'll do a pull request with a suggested fix.

**Comment by fsavje** [comment]
Fixed with #18
