### ISSUE TITLE
Run the windows bat but not working

### ISSUE THREAD

**Issue by rwb196884** [fsavje/math-with-slack#24]
I see `math-with-slack.js` is on disc.

**Comment by goatandsheep** [comment]
[MathJax has shut down](https://www.mathjax.org/cdn-shutting-down/)

**Comment by RONNCC** [comment]
@goatandsheep  but they are using a newcdn now so that shouldn't be a problem

**Comment by RONNCC** [comment]
Can confirm it still works for me

**Comment by goatandsheep** [comment]
Sorry, I'm mistaken.

**Comment by crstnbr** [comment]
Do it manually if the bat isn't working. See [here](https://github.com/fsavje/math-with-slack/issues/25#issuecomment-348948080) and #3.
