### ISSUE TITLE
consider katex instead of mathjax 

### ISSUE THREAD

**Issue by prudhomm** [fsavje/math-with-slack#29]
katex https://khan.github.io/KaTeX/ provides a fast typesetting framework compared to mathjax. Maybe katex does not support (yet) all mathjax support, but it is getting very close.

functions are here https://khan.github.io/KaTeX/function-support.html

katex powers gitter (another chat system)

**Comment by fsavje** [comment]
Thanks for the suggestion. Very interesting indeed. However, it seems that KaTeX isn't function compatible with MathJax yet, and I don't want to break existing functionality. I will definitely consider it once it matures.
