### ISSUE TITLE
Not working anymore since last update

### ISSUE THREAD

**Issue by edebrouwer** [fsavje/math-with-slack#30]
Hello,

The latex rendering stopped working recently. I re-did the instructions several times but still doesn't. My whole team has similar problem on various platforms.

Regards !

Edward

**Comment by fsavje** [comment]
Thanks for the report! I can't replicate the error -- it works as it should on all platforms I've tested. Could you provide more details?

Are you sure that you're using the latest version? I.e., 0.2.3

**Comment by edebrouwer** [comment]
Hi,

Thank you for your quick answer. Indeed, I was running the previous version 0.2.2.. It works fine with the new one. My apologies for bothering !

Thanks for your help and your work !!

Edward

**Comment by edebrouwer** [comment]
Hi,

Thank you for your quick answer. Indeed, I was running the previous version 0.2.2.. It works fine with the new one. My apologies for bothering !

Thanks for your help and your work !!

Edward
