### ISSUE TITLE
no write permission on snap Slack

### ISSUE THREAD

**Issue by zgbkdlm** [fsavje/math-with-slack#35]
My slack in installed by snap.

The location is `/snap/slack/current/usr/lib/slack/resources/app.asar.unpacked/src/static/`

But the snap is read-only system, `sudo` has no permission to write in snap..

The error is:

```
sudo bash math-with-slack.sh
Cannot write to Slack file: /snap/slack/current/usr/lib/slack/resources/app.asar.unpacked/src/static/ssb-interop.js
```

**Comment by fsavje** [comment]
Hi @zgbkdlm and thanks for the report. Snap is not supported by `math-with-slack`. You should however be able to install it if you manage to get write permission in the Snap dir. See Issue #32 for more details.
