### ISSUE TITLE
Stopped working in Slack Version 3.2.0?

### ISSUE THREAD

**Issue by Michielskilian** [fsavje/math-with-slack#36]
Hi,

I used your script for quite some time now and it always worked fine. But now, since a week or so, it's just not rendering anymore. 
I'm not sure if it's the new Slack version (I have v3.2.0 installed)?
I already tried everything like downloading the script again from the Github, re-running the script and checking with some basic math that should normally work.

Thanks in advance for any help!

**Comment by LaurentHayez** [comment]
Hi Kilian,

Me and another user both have this issue with Slack v3.2.0 (and now 3.2.1) on Ubuntu 18.04. Do you also use Ubuntu 18.04 or do you use another OS?

**Comment by KeAWang** [comment]
It doesn't work on Windows 10 with Slack v3.2.0 either

**Comment by Michielskilian** [comment]
Hi Laurent,

I'm using MacOS High Sierra (latest version).

**Comment by fsavje** [comment]
Hi @Michielskilian and thanks for the bug report. Please try this script: https://github.com/fsavje/math-with-slack/blob/d385db532d6698b16a79c6d06fe1bdcb52732888/math-with-slack.sh Please let me know how it works.

(Working on Windows version at the moment, @KeAWang )

**Comment by fsavje** [comment]
@KeAWang Could you please try whether the [updated script](https://github.com/fsavje/math-with-slack/releases/download/v0.2.4/math-with-slack.bat) works, and report back to here?

**Comment by Michielskilian** [comment]
Hi @fsavje, the script you attached works!

Thank you for the quick fix!

**Comment by Servinjesus1** [comment]
Unfortunately the newest version is not working for me in Win10, v3.2.0
![image](https://user-images.githubusercontent.com/8541095/41428106-4ce0c7cc-6fc6-11e8-9eb2-8bef3d95dc4f.png)
A few of the paths aren't working even though the .js files are in the directory. The previous release, v0.2.3 runs without a hitch but none of the math is rendering either way...

**Comment by KeAWang** [comment]
@fsavje It still doesn't seem to work on Windows 10. The new script gives the following errors
```
Using Slack installation at: ...\slack\app-3.2.0\resources\app.asar.unpacked\src\static
The system cannot find the path specified.
FINDSTR: Cannot open ...\slack\app-3.2.0\resources\app.asar.unpacked\src\ssb-interop.js
The system cannot find the path specified.
FINDSTR: Cannot open ...\slack\app-3.2.0\resources\app.asar.unpacked\src\ssb-interop.js
Backup already exists: ...\slack\app-3.2.0\resources\app.asar.unpacked\src\static/ssb-interop.js.mwsbak
Press any key to continue . . .
```

**Comment by fsavje** [comment]
@Servinjesus1 and @KeAWang Thanks for trying it out. I don't have access to a Windows machine atm, so I can't debug this properly. Could you try this script: https://raw.githubusercontent.com/fsavje/math-with-slack/7d7bc39d2723e8c299bff47d4d80d465d044a1af/math-with-slack.bat Thanks!

**Comment by KeAWang** [comment]
Works great now, thanks!

**Comment by fsavje** [comment]
Thanks for checking!
