### ISSUE TITLE
Does not work with Slack from Microsoft Store

### ISSUE THREAD

**Issue by OndrejMarsalek** [fsavje/math-with-slack#39]
I had Slack installed through Microsoft store and the script was not able to find it. I tried looking for the file `ssb-interop.js` to find the directory but got nothing. I don't know where and how the Win 10 app gets installed.

After uninstalling Slack and reinstalling it "by hand", everything works as expected.

**Comment by fsavje** [comment]
Thank you for the bug report. However, this has been addressed before. Microsoft Store does not give write permission to their apps even for administrators. `math-with-slack` will not try to override such restrictions.

See the discussion in the readme for more information:

> ### Package and software managers
> 
> The script needs write permissions in the Slack directory in order to inject the MathJax code. Some package and software managers write protect their directories, and `math-with-slack` cannot be installed if Slack is installed through such a manager. This is the case for both the Windows Store and Snap versions of Slack. You should use the version downloaded from [Slack's website](https://slack.com/downloads/windows) if you want to use `math-with-slack`. The script should, however, work with most package managers if you manage to grant the script write permission.

**Comment by OndrejMarsalek** [comment]
Thank you for pointing that out, I missed it in the readme, sorry about that.

**Comment by fsavje** [comment]
No worries at all. Better safe than sorry when it comes to bug :)
