### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by lobachevzky** [fsavje/math-with-slack#40]
Perhaps I'm missing something basic here:
```
~/soft_actor_critic debug-hindsight
(sac) ❯ curl -OL https://github.com/fsavje/math-with-slack/releases/download/v0.2.5/math-with-slack.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   608    0   608    0     0   2003      0 --:--:-- --:--:-- --:--:--  2013
100  5274  100  5274    0     0   9054      0 --:--:-- --:--:-- --:--:-- 44694

~/soft_actor_critic debug-hindsight
(sac) ❯ sudo bash math-with-slack.sh
Password:
Using Slack installation at: /Applications/Slack.app/Contents/Resources/app.asar.unpacked/src/static
math-with-slack has been installed. Please restart the Slack client.
```
I close and open the slack desktop client and
![image](https://user-images.githubusercontent.com/10344742/44963169-6a18d400-aef6-11e8-84bf-43ca0516bf29.png)

Why is the latex not rendering?

**Comment by fsavje** [comment]
Thank you for the report, @lobachevzky. You seem to have installed the script correctly. A few thing I would check if I were you:

1. Did you install math-with-slack at the place where you're running it from? Slack may, occasionally, be install in several places, and math-with-slack installs itself in the first place it finds. In your case, make sure that you're running Slack installed at /Applications/Slack.app
2. You need to do a proper restart of the application. Just closing the GUI window will not do. You need to completely quit the program (e.g., right-click and then "quit" on a Mac OS), and then start the program. You could also test a hard reboot.
3. Make sure that you have the latest version of Slack installed (at least v3.2.0). Slack recently updated the way the app was loaded, and consequently, the script was rewritten to fit this. As a consequence, the current version of the script does not work with older versions of Slack.

I hope this helps you out.

**Comment by lobachevzky** [comment]
Mysteriously the problem seems to have gone away :/ I actually only have v3.0.5 but math is now rendering properly. I am pretty sure I was closing the application fully. I'm also pretty sure I have Slack installed in one place:

```
❯ locate Slack.app | grep -v /Applications/Slack.app
# returns nothing
```
 🤷‍♂️
