### ISSUE TITLE
Doesn't seem to work any more

### ISSUE THREAD

**Issue by benninkrs** [fsavje/math-with-slack#45]
I installed it a year ago and it worked fine.  Now, equations don't render anymore.  I see this issue has occurred [before](https://github.com/fsavje/math-with-slack/issues/30) and supposedly fixed, but I am having the same problem.

Windows 10
Slack 3.3.8
math-with-slack 0.2.5

**Comment by fsavje** [comment]
Thank you for your report.

math-with-slack 0.2.5 works as it should with Slack 3.3.8 for me.

Have you reinstalled math-with-slack after the Slack update?

**Comment by benninkrs** [comment]
Yes

**Comment by fsavje** [comment]
Ok. Since I can't reproduce the bug, still won't be fix. Please reopen the ticket with a proper bug report and I'll take a look: https://marker.io/blog/write-bug-report/

**Comment by benninkrs** [comment]
1. Close Slack
2. Run math-with-slack script
![terminal](https://user-images.githubusercontent.com/22162695/55413084-a10ba280-5536-11e9-80f0-0319728f097d.png)

[math-with-slack.bat.txt](https://github.com/fsavje/math-with-slack/files/3034580/math-with-slack.bat.txt)

3. Open Slack.
![slack_version](https://user-images.githubusercontent.com/22162695/55413158-c7c9d900-5536-11e9-8fbe-0850859299c9.PNG)

4. Type in TeX markup
![result](https://user-images.githubusercontent.com/22162695/55413149-c5677f00-5536-11e9-99dc-795c34655d61.png)
Expected behavior:  Markup renders as math
Actual behavior:  Markup did not render as math


I also tried uninstalling and re-installing the script, but that did not work either.

**Comment by fsavje** [comment]
Thank you! I still cannot reproduce the bug. I've also asked other people, and they aren't having any problems. And no other users have reported any problems lately. It all points to that you have a problem with your specific installation. I cannot help you with that unfortunately. My recommendation would be to completely uninstall Slack, and reinstall everything.

Hope you manage to get it to work!

**Comment by benninkrs** [comment]
I came in to work this morning and the markup I entered yesterday is now magically rendered as math.  I didn't do anything, but it seems to be working now.  Weird!
