### ISSUE TITLE
Does not work on MacOS Mojave with Slack 3.3.8

### ISSUE THREAD

**Issue by romainhild** [fsavje/math-with-slack#46]
I have followed the install procedure and restarted the client but when writing $e=mc^2$ as a direct message to me, the math are not rendered.
Is there a debug mode in order to have more info ?

**Comment by fsavje** [comment]
Thanks for the report. Your best bet is Slack's DevTools.

Start Slack with:
```
export SLACK_DEVELOPER_MENU=true
open /Applications/Slack.app
```

Then open the DevTools with `⌥⌘I`.

**Comment by romainhild** [comment]
Thanks, I took a quick look, but I have to admit that my competences in javascript are quite limited.
I did a search for `math` and `mws` but couldn't find anything.
Any advice ?

**Comment by fsavje** [comment]
I'm using Slack 3.3.8 on MacOS Mojave, and it works excellently. It is most likely an issue with your specific installation of Slack. My advice is to reinstall Slack and the script from scratch.

**Comment by romainhild** [comment]
indeed reinstalling Slack did it! thanks
