### ISSUE TITLE
\binom, \genfrac fail to render

### ISSUE THREAD

**Issue by awstlaur** [fsavje/math-with-slack#5]
For examples:
```
$$\frac{n!}{k!(n-k)!} = \binom{n}{k}$$
```

```
$\genfrac{}{}{0pt}{}{1}{2}$
```

Both of these render with the command (`\binom`, `\genfrac`) in red. I can provide screenshots if requested. It may be worth noting that both of these commands are defined in the amsmath package. However, [MathJax itself](http://docs.mathjax.org/en/latest/tex.html#supported-latex-commands) appears to support the package.

My environment:

System:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

Slack application: 
```
2.5.2 64-bit Beta Channel
(Walking on a Dream)
```

Node.js: `v6.2.2`
npm: `3.9.5`

**Comment by fsavje** [comment]
Thank you for such a good bug report, @awstlaur! It seems that I missed adding the AMSmath extension. The script is now updated. It should work if you download and run the new version. Please report how it works.

**Comment by awstlaur** [comment]
Works well! Thanks for the quick response.
