### ISSUE TITLE
Install on workspace 

### ISSUE THREAD

**Issue by oshriPP** [fsavje/math-with-slack#52]
Hi, 
I installed the script on my Mac, but the Slack showed the formula as a plain text on my teammates. 
Is there a way to install it in the workspace for all the users?

**Comment by fsavje** [comment]
Hi @oshriPP and thank you for your question!

This is not possible. If it were possible, it would allow for remote code injections. That would be an enormous security risk. You have to ask your team mates to install the script themselves.
