### ISSUE TITLE
Fix loading when switching teams

### ISSUE THREAD

**Issue by fsavje** [fsavje/math-with-slack#8]

**Comment by gauss256** [comment]
It seems to load only for the team that is current when Slack is started. The good news though is that if you have loaded once you can switch to another team, switch back, and it is still loaded.

So a workaround for multiple teams is to switch to the team where it is not yet loaded, then quit and restart Slack. Do this for each team and it works from then on, for all teams.

**Comment by fsavje** [comment]
@gauss256 Team switching should now work. Please let me know if it doesn't.

**Comment by gauss256** [comment]
Works now. Lots of nice changes in v0.2!
