### ISSUE TITLE
The script for windows is not supporting slack version other than 2.5.1.

### ISSUE THREAD

**Issue by NKudryavka** [fsavje/math-with-slack#9]
The script is hard coded version of slack, so when I use other version (such as 2.5.2), searching slack is always fails.

**Comment by fsavje** [comment]
Thank you @NKudryavka for the report! I'll look in to it asap.

**Comment by fsavje** [comment]
@NKudryavka The script has been updated and should now work with 2.5.2 on Windows. Please confirm.

**Comment by NKudryavka** [comment]
Thank you for quick response.
@fsavje 's script worked on Slack 2.5.2 well, but it is still version hard-coded.
So, I made a pull request for fix it.

**Comment by fsavje** [comment]
@NKudryavka Thank you! That's much better than to hard code it.
